#!/bin/bash

# 🎯 QUICK START GUIDE - Run this to see everything working!

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║   🚀 React + MongoDB User Management System Setup Guide    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 DOCUMENTATION FILES (READ FIRST!)${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo -e "${GREEN}✅ START HERE:${NC}"
echo "   📖 README_USER_SYSTEM.md ........... Complete overview"
echo "   📖 SEE_USERS_GUIDE.md ............. How to view users (3 methods)"
echo ""
echo -e "${GREEN}THEN READ:${NC}"
echo "   📖 ADMIN_DASHBOARD_GUIDE.md ....... Dashboard features"
echo "   📖 BACKEND_SETUP.md ............... API endpoints"
echo "   📖 PROJECT_STRUCTURE.md ........... File organization"
echo ""
echo ""

echo -e "${BLUE}🚀 TO RUN THE SYSTEM${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "Terminal 1 - Start Backend:"
echo -e "  ${YELLOW}cd /home/coding/react/backend && npm run dev${NC}"
echo ""
echo "Terminal 2 - Start Frontend:"
echo -e "  ${YELLOW}cd /home/coding/react && npm run dev${NC}"
echo ""
echo "Terminal 3 - View Database:"
echo -e "  ${YELLOW}mongosh${NC}"
echo -e "  ${YELLOW}use react_app${NC}"
echo -e "  ${YELLOW}db.users.find().pretty()${NC}"
echo ""
echo ""

echo -e "${BLUE}🌐 WEBSITE LINKS${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo -e "  ${GREEN}http://localhost:3000${NC} ...................... Home"
echo -e "  ${GREEN}http://localhost:3000/signup${NC} .............. Sign Up (Create Account)"
echo -e "  ${GREEN}http://localhost:3000/login${NC} ............... Login (Test: test@example.com / test123456)"
echo -e "  ${GREEN}http://localhost:3000/admin/dashboard${NC} .... 👥 SEE ALL USERS HERE! ⭐"
echo ""
echo ""

echo -e "${BLUE}🔌 API ENDPOINTS${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "  ${GREEN}http://localhost:5001/api/health${NC} ........... Test API"
echo "  ${GREEN}http://localhost:5001/api/users${NC} ............ Get ALL users (important!)"
echo "  ${GREEN}POST http://localhost:5001/api/auth/register${NC} . Create account"
echo "  ${GREEN}POST http://localhost:5001/api/auth/login${NC} .... Login"
echo ""
echo ""

echo -e "${BLUE}💾 MONGODB COMMANDS${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "  mongosh ............................. Open MongoDB"
echo "  use react_app ....................... Select database"
echo "  db.users.find().pretty() ............ See all users ⭐"
echo "  db.users.countDocuments() ........... Count total users"
echo "  db.users.find({ email: 'test@example.com' }) ... Find by email"
echo ""
echo ""

echo -e "${BLUE}👤 TEST ACCOUNT${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "  Email:    test@example.com"
echo "  Password: test123456"
echo "  Use this to login and test the admin dashboard!"
echo ""
echo ""

echo -e "${BLUE}📊 ADMIN DASHBOARD FEATURES${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "  ✅ View all registered users"
echo "  ✅ Search by name or email"
echo "  ✅ See user details with social links"
echo "  ✅ Delete user accounts"
echo "  ✅ View statistics (total, verified, admins)"
echo "  ✅ See registration dates"
echo ""
echo ""

echo -e "${BLUE}🗂️ WHAT WAS CREATED${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "  Frontend:"
echo "    ✅ AdminDashboard.jsx - See all users"
echo "    ✅ Updated Navbar with Admin button"
echo ""
echo "  Backend:"
echo "    ✅ MongoDB connection (server.js)"
echo "    ✅ User schema (models/User.js)"
echo "    ✅ Authentication routes (authRoutes.js)"
echo "    ✅ User management endpoints (userRoutes.js)"
echo ""
echo "  Database:"
echo "    ✅ MongoDB collection: users"
echo "    ✅ All user data stored (name, email, phone, location, etc.)"
echo ""
echo "  Documentation:"
echo "    ✅ 5 comprehensive guides"
echo "    ✅ API examples"
echo "    ✅ MongoDB queries"
echo ""
echo ""

echo -e "${BLUE}💡 3 WAYS TO SEE REGISTERED USERS${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "  1️⃣ Admin Dashboard (Most User-Friendly)"
echo "     Visit: http://localhost:3000/admin/dashboard"
echo "     See all users in a beautiful table!"
echo ""
echo "  2️⃣ Backend API (For Developers)"
echo "     curl http://localhost:5001/api/users"
echo "     Get JSON response with all users"
echo ""
echo "  3️⃣ MongoDB Direct (For Database Admins)"
echo "     mongosh → use react_app → db.users.find().pretty()"
echo "     Raw database documents"
echo ""
echo ""

echo -e "${BLUE}🔐 SECURITY FEATURES${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "  ✅ Passwords encrypted with bcryptjs"
echo "  ✅ JWT authentication (7-day tokens)"
echo "  ✅ Input validation on all fields"
echo "  ✅ CORS protection"
echo "  ✅ Email uniqueness enforced"
echo "  ✅ Protected API routes"
echo ""
echo ""

echo -e "${BLUE}📝 STUDENT NOTES${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "  When users sign up and enter their data, it's:"
echo "    1. Validated (email, password rules)"
echo "    2. Encrypted (password hashing)"
echo "    3. Saved to MongoDB database"
echo "    4. Accessible via Admin Dashboard"
echo "    5. Viewable as JSON via API"
echo ""
echo "  Database Fields Stored:"
echo "    • Full Name"
echo "    • Email"
echo "    • Password (encrypted)"
echo "    • Phone"
echo "    • Location"
echo "    • Bio"
echo "    • Social Links (Google, GitHub, Facebook, LinkedIn)"
echo "    • Verification Status"
echo "    • User Role"
echo ""
echo ""

echo -e "${YELLOW}🎯 QUICK TEST WORKFLOW${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "1. Start all 3 terminals (backend, frontend, MongoDB)"
echo "2. Go to http://localhost:3000/signup"
echo "3. Create an account with your info"
echo "4. Your data is NOW in MongoDB!"
echo "5. Go to http://localhost:3000/admin/dashboard"
echo "6. See yourself listed in the table!"
echo "7. Click 'View' to see your complete profile"
echo "8. In mongosh: db.users.find() - See raw database"
echo ""
echo ""

echo -e "${GREEN}✨ YOU'RE ALL SET!${NC}"
echo "───────────────────────────────────────────────────────────"
echo ""
echo "   Start with the documentation files above."
echo "   Then run the commands to see everything working!"
echo ""
echo "   Happy coding! 🎉"
echo ""
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
